# Generated by Django 4.2.15 on 2024-09-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_team_coach"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="total_participation",
        ),
        migrations.RemoveField(
            model_name="team",
            name="total_wins",
        ),
        migrations.AddField(
            model_name="team",
            name="team_participation",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="team_wins",
            field=models.IntegerField(default=0),
        ),
    ]
