# Generated by Django 4.2.15 on 2024-09-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_playerdetails_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerdetails",
            name="total_participation",
        ),
        migrations.RemoveField(
            model_name="playerdetails",
            name="total_wins",
        ),
        migrations.AddField(
            model_name="playerdetails",
            name="individual_participation",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerdetails",
            name="individual_wins",
            field=models.IntegerField(default=0),
        ),
    ]
