# Generated by Django 4.2.15 on 2024-08-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="round",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="round",
            name="match_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="round",
            unique_together={("match_number", "game")},
        ),
    ]
