# Generated by Django 4.2.15 on 2024-08-31 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0002_alter_round_unique_together_round_match_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="leagues.league",
            ),
        ),
    ]
