# Generated by Django 4.2.15 on 2024-08-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        ("leagues", "0003_alter_round_league"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="round",
            unique_together={("round_number", "match_number", "game")},
        ),
    ]
